### ISSUE TITLE
FATE: Support custom stress bars

### ISSUE THREAD

**Issue by gadse** [Phoenox/dorc#6]
Example: Heat stress for Mechs in Mechwarrior

Not sure if this will go into the fate system or a separate system. Code-wise, ome kind of mixin might be nice. E.g. a Mechwarrior-Character inheriting from the fate character and adding (through composition) a custom stress "module" (object, struct, whatever gets the job done well).

**Comment by Phoenox** [comment]
I'd say MechWarrior is definitely its own system. But yes, especially the `Character` class should probably inherit the Fate Core `Character` and extend on it.

**Comment by gadse** [comment]
Closed in favor of followup ticket(s).
